misc Makefile and get-smf-web-pages fixes

diff --git a/bin/get-smf-web-pages b/bin/get-smf-web-pages
--- a/bin/get-smf-web-pages
+++ b/bin/get-smf-web-pages
@@ -1,9 +1,14 @@
 #!/bin/bash
-export PATH+=":$PWD"
+BIN_DIR=`readlink -f ../bin`
+export PATH+=":${BIN_DIR}"
 base_url="http://ogres-crypt.com/SMF"
 [ -d SMF ] && rm -rf SMF
 # -k: convert to relative links
 wget -o fetch.log -m -nH -np -k http://ogres-crypt.com/SMF
+if ! [ -d SMF ]; then
+  echo "Download of SMF directory failed."
+  exit 2
+fi
 cd SMF
 # Get icons which are actually in ../icons.  Ignore .html indexes.
 wget -a ../fetch.log -m -nH -np -A ico http://ogres-crypt.com/icons/
@@ -21,9 +26,9 @@ if ! [ -e icons/folder.png ]; then
 'http://files.softicons.com/download/internet-icons/stuttgart-icons-by-pc.de/png/32/folder.png' \
   -O icons/folder.png
   # Re-size to 16x16, transparent background.
-  convert -resize 16x16 -fill none -fuzz 20% \
-    -draw 'matte 0,0 floodfill' \
-    icons/folder.png icons/folder.png
+  # convert -resize 16x16 -fill none -fuzz 20% \
+  #  -draw 'matte 0,0 floodfill' \
+  # icons/folder.png icons/folder.png
 fi
 if ! [ -e icons/fopen.png ]; then
   # http://files.softicons.com/download/toolbar-icons/childish-icons-by-double-j-design/png/32x32/childish_Folder.png
@@ -33,9 +38,9 @@ if ! [ -e icons/fopen.png ]; then
   'http://files.softicons.com/download/toolbar-icons/childish-icons-by-double-j-design/png/32x32/childish_Folder.png' \
   -O icons/fopen.png
   # Re-size to 16x16, transparent background.
-  convert -resize 16x16 -fill none -fuzz 20% \
-    -draw 'matte 0,0 floodfill' \
-    icons/fopen.png icons/fopen.png
+  # convert -resize 16x16 -fill none -fuzz 20% \
+  # -draw 'matte 0,0 floodfill' \
+  # icons/fopen.png icons/fopen.png
 fi
 if [ -f Documentation ]; then
   mv Documentation Documentation.html
@@ -72,12 +77,18 @@ if [ -f Documentation ]; then
   # Remove refs to missing target.
   sed -i -e '\|<li>See the.*SMF-Template-SMFTech-Beta.xls.|d' \
     smfTech-Function.html
+  while read f; do
+    sed -i \
+    -e 's|<!-- text below generated by server. PLEASE REMOVE -->.*||g' "$f"
+  done < <(grep -ilr 'text below generated by server' .)
+  find . -maxdepth 1 -name 'view*' -delete
+  cd ..
 fi
-while read f; do
-  sed -i \
--e 's|<!-- text below generated by server. PLEASE REMOVE -->.*||g' $f
-done < <(grep -ilr 'text below generated by server' .)
-cd ..
+if [ "`find . -maxdepth 1 -name 'RCH_Stock_Market_Functions*.zip' | \
+         wc -1`" -ne 1 ]; then
+  echo "can't find RCH_Stock_Market_Functions zip file"
+  exit 2
+fi
 mkdir 'SMF Add-In' && cd "$_"
 unzip ../RCH_Stock_Market_Functions*.zip
 # The zip file is more up-to-date than the Elements directory.
